# Array

## 1. Array

In [1]:
import array

In [8]:
arr1 = array.array('i',[12,9,4,98,9])
type(arr1)

array.array

In [9]:
# Insertion
arr1.insert(2,-2)
arr1

array('i', [12, 9, -2, 4, 98, 9])

In [10]:
# deletion
arr1.remove(98)
arr1

array('i', [12, 9, -2, 4, 9])

In [11]:
# updation
arr1[2] = 2
arr1

array('i', [12, 9, 2, 4, 9])

In [18]:
# sorting
array.array("i",sorted(arr1))

array('i', [2, 4, 9, 9, 12])

In [20]:
# merging
arr2 = array.array("i",[11,12,13,90])
arr1+arr2

array('i', [12, 9, 2, 4, 9, 11, 12, 13, 90])

In [21]:
# splitting
arr1[:2]

array('i', [12, 9])

## 2. Numpy Array

In [23]:
import numpy as np

In [33]:
arr1 = np.array([12,8,5,0])
arr1

array([12,  8,  5,  0])

In [34]:
# Insertion
np.insert(arr1,-2,23)

array([12,  8, 23,  5,  0])

In [35]:
# Deletion
np.delete(arr1,1)

array([12,  5,  0])

In [36]:
# Updation
arr1[0]=1
arr1

array([1, 8, 5, 0])

In [37]:
# Sorting
np.sort(arr1)

array([0, 1, 5, 8])

In [39]:
# merging
arr2 = np.array([99,98,76])
np.concatenate([arr1,arr2])

array([ 1,  8,  5,  0, 99, 98, 76])

In [52]:
# splitting
np.split(arr1,2)

[array([1, 8]), array([5, 0])]